INSERT INTO LECTURE (LECTURE_NAME,LECTURE_DESCRIPTION) VALUES ('Test Lecture','Test Description');
INSERT INTO LECTURE (LECTURE_NAME,LECTURE_DESCRIPTION) VALUES ('Test Lecture 2','Test Description 2');
INSERT INTO REG_USER (FULL_NAME, PASSWORD, PHONE_NUMBER, ROLE, USERNAME) VALUES ('Teacher1', '{noop}1234', '12345678', 'ROLE_ADMIN', 't1234');
INSERT INTO REG_USER (FULL_NAME, PASSWORD, ROLE, USERNAME) VALUES ('Student1', '{noop}1234', 'ROLE_USER', 's1234');