INSERT INTO PUBLIC.LECTURE (LECTURE_NAME) VALUES ('Test Lecture');
INSERT INTO PUBLIC.LECTURE (LECTURE_NAME) VALUES ('Test Lecture 2');
INSERT INTO PUBLIC.REG_USER (FULL_NAME, PASSWORD, PHONE_NUMBER, ROLE, USERNAME) VALUES ('Teacher1', '{noop}1234', '12345678', 'ROLE_ADMIN', 't1234');
INSERT INTO PUBLIC.REG_USER (FULL_NAME, PASSWORD, ROLE, USERNAME) VALUES ('Student1', '{noop}1234', 'ROLE_USER', 's1234');